name: CI

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    # TODO: укажите нужные permissions для GITHUB_TOKEN
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # TODO: укажите нужные значения для action setup-java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build & Deploy
        run:
          mvn -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
